STKSEG SEGMENT STACK
    DW 32 DUP(0)
STKSEG ENDS

DATASEG SEGMENT
    MSG DB "Hello World$", 0  ; 最后添加一个空字符，以便字符串正确终止
DATASEG ENDS

CODESEG SEGMENT
ASSUME CS:CODESEG, DS:DATASEG, SS:STKSEG

MAIN PROC FAR
    MOV AX, DATASEG
    MOV DS, AX
    
    MOV AH, 9h  ; 正确的十六进制表示
    MOV DX, OFFSET MSG
    INT 21h
    
    MOV AX, 4C00h
    INT 21h
MAIN ENDP

CODESEG ENDS
END MAIN